[package]
name = "hoive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-spiral ="0.1.0" # supports converting to and from hex spiral coords

rand = "0.8.5"  # For randomising which player goes first
serde = "1.0.126"
serde_json = "1.0.64"
diesel = { version = "1.4.6", features =["sqlite", "r2d2"]} # managing the various game sessions in sqlite db
dotenv = "0.15.0"   # required by diesel
actix = "0.11.0"
actix-web = "3.3.2"

#actix-rt = "1.1.1"
#actix-files = "0.5.0"
#actix-session = "0.4.1"
#bytes = "1.0.1"
#itertools = "0.10.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] } # generate user ids
#log = "0.4.11"
serde_derive = "1.0"

# For benchmarking

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark3"
harness = false