[package]
name = "hoive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"  # For randomising which player goes first

# For benchmarking

#[dev-dependencies]
#criterion = "0.3"

#[[bench]]
#name = "benchmark1"
#harness = false